spring:
  application:
    name: radar-scene
  datasource:
    url: jdbc:postgresql://localhost:5432/radarscene
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: 7A25432A462D4A614E645267556B58703273357638792F423F4428472B4B6250
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Logging
logging:
  level:
    root: INFO
    com.radarscene: DEBUG
    org.springframework.security: INFO
    
# OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
